
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?s ?p ?o 
WHERE 
{
  ?s a owl:AnnotationProperty .
  FILTER(NOT EXISTS {?s rdfs:label ?x .})
  ?s ?p ?o .
}
